lua require('plugins')
set showmatch 
set hlsearch 
set expandtab 
set tabstop=4
set softtabstop=4
set expandtab 
set shiftwidth=4
set autoindent 
set relativenumber 
syntax on 
set cursorline
lua require('el').setup()
